modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="the_star_wars_saga_mod"
version="1.0.0"
displayName="the star wars saga mod"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="Jem, MCreator"

[[dependencies.the_star_wars_saga_mod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




